export const UI_CONSTANTS = {
  TIMEOUTS: {
    ANIMATION_DELAY: 300,
    UNDO_TIMEOUT: 5000,
  },
  DIMENSIONS: {
    TRANSACTION_CARD_HEIGHT: 120,
    SCROLL_TO_TOP_THRESHOLD: 300,
  },
  PERFORMANCE: {
    SCROLL_THROTTLE: 16,
    INITIAL_RENDER_COUNT: 10,
    BATCH_SIZE: 20,
    WINDOW_SIZE: 10,
    UPDATE_BATCHING_PERIOD: 100,
  }
} as const; 